# Netlify build configuration for a Next.js project

[build]
  # Command to build the project
  command = "pnpm build"

  # Directory to publish
  publish = ".next"

[[plugins]]
  # Essential Next.js plugin for Netlify
  package = "@netlify/plugin-nextjs"
